### ISSUE TITLE
Add a controller for getting open data sets dynamically

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/IFTTT-Edmonton#55]
We have quite a bit of work related to open data and IFTTT popping up. We need a controller that pulls a list of open data sets. Look [here](https://github.com/CityofEdmonton/IFTTT-Edmonton/blob/master/src/controllers/air-quality-stations.js) to see how we handle dynamically pulling our cities that have air quality stations.

This would involve dynamically pulling [this](https://data.edmonton.ca/data.json) set of data. Check out [this SO post](https://stackoverflow.com/questions/29783413/is-there-a-socrata-api-for-reading-a-sites-catalog) for more information. 

We also need to let user's set which column in a dataset they want to watch, so we would need a controller that takes the data set identifier, then returns a list of columns for that dataset.

**Comment by j-rewerts** [comment]
Check out [this post](https://stackoverflow.com/questions/24745820/socrata-get-data-types-of-dataset-columns) on getting data types.

**Comment by j-rewerts** [comment]
In terms of pulling the columns from open data, we have ~1000 open data sets, so we will need to make 1000 calls to pull all that info. Lucky for us, we have Redis!

To start, hit each data set one at a time. Use a Redis key of opendata/sets/"hashed data set name here". Collect all the columns and [rpush](https://redis.io/commands/rpush) it to a list with the previously mentioned key. [Set an expiry time](https://redis.io/commands/expire) on the key.

**Comment by j-rewerts** [comment]
Since we have ~1000 datasets, say 15 columns per dataset, each column has a name of 20 characters and each character takes up 2 bytes, we should have 600KB-1MB of data usage for this service. That won't be too bad.

**Comment by WJXHenry** [comment]
Here's the [docs](https://dev.socrata.com/docs/endpoints.html) on the Socrata API endpoints. You *are* able to pass in parameters to filter the data using [filters](https://dev.socrata.com/docs/filtering.html) or [SoQL](https://dev.socrata.com/docs/queries/).
