### ISSUE TITLE
Max Redis list size is off by one

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/IFTTT-Edmonton#81]
In production, we're currently saving a max of 5 of the most recent records. When you view the Redis keys that are active enough to fill that space, they actually have 6 records in the list.

**Comment by WJXHenry** [comment]
@j-rewerts Not sure if this might be the problem but I came across this environment variable: https://github.com/CityofEdmonton/IFTTT-Edmonton/blob/0f3fd5ae15d57db641772a10fd6409d0633c14fd/src/server.js#L25

**Comment by j-rewerts** [comment]
Yeah that's the one. Track that to our Redis access layer. I must have an off by one error there.

**Comment by j-rewerts** [comment]
await this.client.ltrim(key, 0, this.maxElements)
This line in change writer. 

It must be inclusive and I thought it was exclusive.
